changelog:
  exclude:
    authors:
      - pre-commit-ci
      - renovate
      - dependabot
  categories:
    - title: "Breaking changes"
      labels: [breaking]
    - title: "Features"
      labels: [feature]
    - title: "Bug Fixes"
      labels: [bugfix]
    - title: "Miscellaneous"
      labels: [miscellaneous]
    - title: "Documentation"
      labels: [documentation]
    - title: "Dependencies"
      labels: [dependencies]
    - title: "Uncategorized"
      labels: ["*"]
