ci:
  skip: [pyright]
  autoupdate_schedule: quarterly
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # File names
      - id: check-case-conflict
      # File formats
      - id: pretty-format-json
      - id: check-json
      - id: check-toml
      - id: check-yaml
      # Executables
      - id: check-executables-have-shebangs
        exclude: dev-env
      - id: check-shebang-scripts-are-executable
      # Git shenanigans
      - id: check-merge-conflict
      - id: check-added-large-files
      # Python issues
      - id: check-ast
      - id: debug-statements
      # Whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.355
    hooks:
      - id: pyright
        additional_dependencies:
          - poetry==1.8.2
          - ruamel-yaml==0.18.6
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 9db9854e3041219b1eb619872a2dfaf58adfb20b  # v1.8.0
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]
        additional_dependencies:
          - poetry==1.8.2
          - pytest==8.1.1
          - ruamel-yaml==0.18.6
